name:                stash
version:             0.3.0
github:              "rorokimdim/stash"
license:             BSD3
author:              "Amit Shrestha"
copyright:           "2020 Amit Shrestha"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rorokimdim/stash#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- ansi-wl-pprint
- SHA
- base64-bytestring
- bencode
- brick
- bytestring
- containers
- crypto-simple
- cryptonite
- data-default
- Diff
- directory
- editor-open
- entropy
- filepath
- fuzzy
- haskeline
- Hclip
- io-memoize
- logging
- mtl
- optparse-applicative
- random
- random-strings
- raw-strings-qq
- sqlite-simple
- tabl
- text
- time
- unordered-containers
- vector
- vty

library:
  source-dirs: src

default-extensions:
- BangPatterns
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies

executables:
  stash:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stash
    when:
    - condition: false
      other-modules: Paths_stash

tests:
  stash-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stash
    - quickcheck-instances
    - tasty
    - tasty-hunit
    - tasty-quickcheck

benchmarks:
  stash-benchmark:
    main: bench.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stash
    - criterion
