#!/usr/bin/env bash

CLASSPATH=$(clojure -Spath)

if command -v rlwrap &> /dev/null
then
    BABASHKA_PRELOADS='(load-file "stash.clj")' rlwrap -r -q '\"' -b "(){}[],^%#@\";:'" bb --classpath "$CLASSPATH" "$@"
else
    BABASHKA_PRELOADS='(load-file "stash.clj")' bb --classpath "$CLASSPATH" "$@"
fi
