#!/usr/bin/env bash

# Prompt for encryption key
echo -n "Enter encryption key: "
read -rs ekey

PY_COMMAND="python3"
if command -v ipython3 &> /dev/null
then
    PY_COMMAND="ipython3"
fi

STASH_ENCRYPTION_KEY=$ekey STASH_COMMAND_FULL_PATH=$(which stash) $PY_COMMAND -i stash.py
