#!/usr/bin/env bash

CLASSPATH=$(clojure -Spath)

# Prompt for encryption key
echo -n "Enter encryption key: "
read -rs ekey

BB_COMMAND="bb"
if command -v rlwrap &> /dev/null
then
    BB_COMMAND="rlwrap bb"
fi

STASH_ENCRYPTION_KEY=$ekey BABASHKA_PRELOADS='(load-file "stash.clj")' $BB_COMMAND --classpath "$CLASSPATH" "$@"
