#!/usr/bin/env bash

CLASSPATH=$(clojure -Spath)

# Prompt for encryption key
echo -n "Enter encryption key: "
read -rs ekey

if command -v rlwrap &> /dev/null
then
    STASH_ENCRYPTION_KEY=$ekey BABASHKA_PRELOADS='(load-file "stash.clj")' rlwrap -r -q '\"' -b "(){}[],^%#@\";:'" bb --classpath "$CLASSPATH" "$@"
else
    STASH_ENCRYPTION_KEY=$ekey BABASHKA_PRELOADS='(load-file "stash.clj")' bb --classpath "$CLASSPATH" "$@"
fi
